### ISSUE TITLE
Issue on registering settings

### ISSUE THREAD

**Issue by Glunty** [MrVauxs/pf2e-jb2a-macros#20] opened 2022-09-10 21:06 UTC
Hello, 
I think the hook used here is not the one to use : https://github.com/MrVauxs/pf2e-jb2a-macros/blob/fa6a52ef00d41138719354fe66fef969c73e3b82/module/module.js#L3

I get this message when I load the world
![image](https://user-images.githubusercontent.com/18362479/189501559-460b5906-2318-42b9-8e04-3212f27d5ceb.png)

Perhaps "pf2e.systemReady" instead of "init" ? 

Configuration : 
Foundry V10.285
System : PF2E 4.0.0-beta3
pf2e-jb2e-macros : 1.11.1

**Comment by MrVauxs** [comment] 2022-09-10 22:30
The error you copied refers to the on `renderSettings` hook, rather than the `init`.

https://github.com/MrVauxs/pf2e-jb2a-macros/blob/fa6a52ef00d41138719354fe66fef969c73e3b82/module/module.js#L78

Not sure why you are getting that error, certainly unable to reproduce it.

**Comment by MrVauxs** [comment] 2022-09-10 22:43
Did this error happen when entering the world as a player?

**Comment by Glunty** [comment] 2022-09-10 22:46
Yes my bad it is on renderSettings.
Happens when I'm entering world as GM.

I put a debug point to be sure what setting was causing the error stack, it is the set of smallTokenScale done line 79.

It's weird, seems like on my installation the hook for renderSettings is called before the game is ready.

**Comment by MrVauxs** [comment] 2022-09-10 23:17
Yeah that is certainly strange. Does it happen without any other modules on? If not, check what other modules may be interacting with PF2e x JB2A Macros.

**Comment by Glunty** [comment] 2022-09-11 09:14
It doesnt matter if I have only this module or others, happens all the time.

I'll do complementary tests when I get some time to restore my dev environment (It is broken since the PF2E github migration :) ). Meanwhile, it doesn't have any impact and I can live with a stack trace in the logs.

**Comment by MrVauxs** [comment] 2022-09-14 13:28
This should hopefully be fixed by moving from `renderSettings` to `ready`.

**Closed by MrVauxs** 2022-09-14 13:28 UTC
Labels: bug, can't replicate

**Comment by Glunty** [comment] 2022-09-14 14:36
No stack anymore with the new version
