### ISSUE TITLE
Bug: Encumbered turning token invisible

### ISSUE THREAD

**Issue by DanielKispert** [MrVauxs/pf2e-jb2a-macros#99] opened 2023-01-26 08:31 UTC
When an actor becomes encumbered, their token turns invisible:
Before: 
<img width="257" alt="image" src="https://user-images.githubusercontent.com/34270661/214789915-a796ff22-91ff-4324-a12a-a6db84bfd9db.png">
After: 
<img width="289" alt="image" src="https://user-images.githubusercontent.com/34270661/214789991-efb0ad9a-5d0a-40ba-879d-fb4f462807d9.png">

Running pf2e animations 2.9.8 and jb2a 0.5.3, the rest of the required modules is also on their latest version.

**Comment by MrVauxs** [comment] 2023-01-26 13:23
Duplicate of #97, will be fixed.

**Closed by MrVauxs** 2023-01-26 13:23 UTC
